from constants.motor import MOVE_AHEAD, MOVE_BACK, MOVE_LEFT, MOVE_RIGHT, ROTATE_RIGHT, ROTATE_LEFT

AI2THOR_NOOP = 'Done'
AI2THOR_CROUCH = "Crouch"

AI2THOR_MOVE_AHEAD = 'MoveAhead'
AI2THOR_MOVE_BACK = 'MoveBack'
AI2THOR_MOVE_LEFT = 'MoveLeft'
AI2THOR_MOVE_RIGHT = 'MoveRight'

MOVEMENT_TO_AI2THOR_MOVEMENT = {
  MOVE_AHEAD: AI2THOR_MOVE_AHEAD,
  MOVE_BACK:  AI2THOR_MOVE_BACK,
  MOVE_LEFT:  AI2THOR_MOVE_LEFT,
  MOVE_RIGHT: AI2THOR_MOVE_RIGHT
}

AI2THOR_ROTATE_RIGHT = 'RotateRight'
AI2THOR_ROTATE_LEFT = 'RotateLeft'

ROTATE_TO_AI2THOR_ROTATE = {
  ROTATE_RIGHT: AI2THOR_ROTATE_RIGHT,
  ROTATE_LEFT: AI2THOR_ROTATE_LEFT
}