# depth camera modes
# ref: https://stackoverflow.com/questions/12819599/freenect-depth-registered-has-no-effect-with-libfreenect
FREENECT_DEPTH_10BIT = 1
FREENECT_DEPTH_11BIT_PACKED = 2
FREENECT_DEPTH_10BIT_PACKED = 3
FREENECT_DEPTH_REGISTERED = 4
FREENECT_DEPTH_MM = 5
FREENECT_DEPTH_DUMMY = 2147483647

# led modes
# ref: https://github.com/OpenKinect/libfreenect/blob/09a1f098040d00e6070c18174904547ec31d2774/wrappers/python/freenect.pyx#L54
FREENECT_LED_OFF = 0
FREENECT_LED_GREEN = 1
FREENECT_LED_RED = 2
FREENECT_LED_YELLOW = 3
FREENECT_LED_BLINK_GREEN = 4
FREENECT_LED_BLINK_RED_YELLOW = 5

FREENECT_LED_MODES = list(range(6))
FREENECT_LED_MODE_DESCIPTIONS = [
  "FREENECT_LED_OFF",
  "FREENECT_LED_GREEN",
  "FREENECT_LED_RED",
  "FREENECT_LED_YELLOW",
  "FREENECT_LED_BLINK_GREEN",
  "FREENECT_LED_BLINK_RED_YELLOW"
]

LOOKING_UP = 'up'
LOOKING_STRAIGHT = 'straight'
LOOKING_DOWN = 'down'
