version: '3.4'
services:
  # Weaver Vector DB Module
  vector-db-module:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '5000'
    - --scheme
    - http
    image: semitechnologies/weaviate:1.22.7
    ports:
    - 5000:5000
    - 50051:50051
    volumes:
    - vector_db_data:/var/lib/vector_db
    restart: on-failure:0
    environment:
      CONTEXTIONARY_URL: contextionary:9999
      IMAGE_INFERENCE_API: 'http://i2v-neural:8080'
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/vector_db'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-contextionary'
      ENABLE_MODULES: 'text2vec-contextionary,img2vec-neural'
      CLUSTER_HOSTNAME: 'node1'
    depends_on: [contextionary, i2v-neural]
  contextionary:
    environment:
      OCCURRENCE_WEIGHT_LINEAR_FACTOR: 0.75
      EXTENSIONS_STORAGE_MODE: weaviate
      EXTENSIONS_STORAGE_ORIGIN: http://vector-db-module:5000
      NEIGHBOR_OCCURRENCE_IGNORE_PERCENTILE: 5
      ENABLE_COMPOUND_SPLITTING: 'false'
    image: semitechnologies/contextionary:en0.16.0-v1.2.1
    ports:
    - 9999:9999
  i2v-neural:
    image: semitechnologies/img2vec-pytorch:resnet50
    environment:
      ENABLE_CUDA: '0'
volumes:
  vector_db_data: