control_api.read_left_sensor() # return 1.0, meaning that the left proximity sensor is reading that the nearest object on the left is approximately 1.0 meter away
control_api.read_right_sensor() # return 0.0, meaning that the right proximity sensor is reading that the robot is touching something on the right
control_api.read_ahead_sensor() # ...
control_api.read_back_sensor() # ...
