control_api.tilt_up() # this is used to make gptpet tilt up with its camera
control_api.tilt_straight() # this is used to make gptpet tilt straight forward with its camera
control_api.tilt_down() # etc ...
